services:
  musicstreamingservice:
    image: musicstreamingservice
    build:
      context: .
      dockerfile: MusicStreamingService/Dockerfile
    networks:
      - common
  postgres:
    image: postgres:18-alpine
    volumes:
      - pgdata:/data/postgres
    env_file:
      - ./env/postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - common
  s3:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    container_name: s3
    hostname: s3
    env_file:
      - "./env/minio.env"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - common
    command: server /data --console-address ":9001"
    
volumes:
  pgdata:
  minio_data:

networks:
  common:
